"""add is_unit and unit_label to products

Revision ID: b6c6a25b092b
Revises: a7b8c9d0e1f2
Create Date: 2026-06-22 17:53:21.719840

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c6a25b092b'
down_revision: str | None = 'a7b8c9d0e1f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_about',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('banner_image_path', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=128), server_default=sa.text("'Чайное Дерево'"), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_about'))
    )
    op.add_column('categories', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('orders', sa.Column('payment_link', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('tracking_link', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('feedback_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('orders', 'status_delivery')
    op.drop_column('orders', 'status_payment')
    op.add_column('pickup_points', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('pickup_points', sa.Column('street', sa.String(length=128), nullable=True))
    op.add_column('pickup_points', sa.Column('building', sa.String(length=32), nullable=True))
    op.add_column('pickup_points', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('pickup_points', sa.Column('map_embed_src', sa.String(length=512), nullable=True))
    op.alter_column('pickup_points', 'work_hours',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.add_column('products', sa.Column('is_unit', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.add_column('products', sa.Column('unit_label', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit_label')
    op.drop_column('products', 'is_unit')
    op.alter_column('pickup_points', 'work_hours',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('pickup_points', 'map_embed_src')
    op.drop_column('pickup_points', 'comment')
    op.drop_column('pickup_points', 'building')
    op.drop_column('pickup_points', 'street')
    op.drop_column('pickup_points', 'city')
    op.add_column('orders', sa.Column('status_payment', sa.VARCHAR(length=32), nullable=False))
    op.add_column('orders', sa.Column('status_delivery', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('orders', 'feedback_sent_at')
    op.drop_column('orders', 'tracking_link')
    op.drop_column('orders', 'payment_link')
    op.drop_column('orders', 'status')
    op.drop_column('categories', 'image_path')
    op.drop_table('site_about')
    # ### end Alembic commands ###
